### ISSUE TITLE
"too many open files"

### ISSUE THREAD

**Issue by judell** [turbot/steampipe-plugin-hackernews#26]
This seems to happen a lot on `select * from hackernews_item`. Reducing `max_items` from 5000 to 500 seems to resolve it, but what would prevent it from happening so you could retrieve 1000s of items?

> 2022-06-20 19:15:34.185 UTC [ERROR] steampipe-plugin-hackernews.plugin: [ERROR] 1655752531209: hackernews_top_story.getT
opStory: query_error="Error while fetching posts story : Get "https://hacker-news.firebaseio.com/v0/item/31809682.json?p
rint=pretty": dial tcp [2600:1901:0:94b6::]:443: socket: too many open files"

**Comment by frederikfab** [comment]
getting the same error message here: https://github.com/turbot/steampipe-plugin-gcp/issues/396 don't know if its related.
